Talend/apache-camel

Jenkinsfile.talend, components/camel-dozer/pom.xml, components/camel-dozer/src/main/java/org/apache/camel/component/dozer/DozerEndpoint.java, components/camel-dozer/src/main/java/org/apache/camel/converter/dozer/DozerBeanMapperConfiguration.java, components/camel-dozer/src/main/java/org/apache/camel/converter/dozer/MapperFactory.java, parent/pom.xml, platforms/karaf/features/src/main/resources/features.xml, platforms/spring-boot/spring-boot-dm/camel-spring-boot-dependencies/pom.xml, pom.xml
Backport of https://issues.apache.org/jira/browse/CAMEL-12440
=> TESB-23868 Issue deploying a route with camel-dozer

pom.xml
upgrade to camel 2.25.2.
When apply patch from tesb/2.24.2, upgrade jackson from 2.10.1 to 2.10.4 so that align with the one from CXF 3.3.7
=> upgrade jackson2 to 2.10.4

platforms/karaf/features/src/main/resources/features.xml, pom.xml
fix error when
`karaf@root()> feature:repo-add camel 2.25.2
karaf@root()> feature:install camel-jacksonxml`
Error:
`Error executing command: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=camel-jacksonxml; type=karaf.feature; version="[2.25.2,2.25.2]"; filter:="(&(osgi.identity=camel-jacksonxml)(type=karaf.feature)(version>=2.25.2)(version<=2.25.2))" [caused by: Unable to resolve camel-jacksonxml/2.25.2: missing requirement [camel-jacksonxml/2.25.2] osgi.identity; osgi.identity=org.apache.camel.camel-jacksonxml; type=osgi.bundle; version="[2.25.2,2.25.2]"; resolution:=mandatory [caused by: Unable to resolve org.apache.camel.camel-jacksonxml/2.25.2: missing requirement [org.apache.camel.camel-jacksonxml/2.25.2] osgi.wiring.package; …
=> TESB-30463 patch for camel-jacksonxml(TESB-30553 CAMEL-15596)

parent/pom.xml, pom.xml
Update of Camel 2.24.2 dependencies with known CVE.
=> TESB-30238 Update vulnerable Camel dependencies.

parent/pom.xml, pom.xml
Update Camel dependencies with CVE.
=> TESB-30238 Update of vulnerable Camel dependencies.

Jenkinsfile.talend, camel-core/pom.xml, camel-core/src/main/java/org/apache/camel/processor/idempotent/FileIdempotentRepository.java, platforms/karaf/features/src/main/resources/features.xml, pom.xml
This reverts commit 3471c4aea72615afbe74449e9116dfc97750be29.
=> Revert "bugfix(TESB-30779): High CPU consumption by ESB routes in 7.3.1 version"

platforms/karaf/features/src/main/resources/features.xml, pom.xml
- https://jira.talendforge.org/browse/TPRUN-5024
- 
jruby embeds snakeyaml libraries with CVEs
Empty the feature (removal could cause hangs during update)
🎾 **Impacts**
=> fix(TPRUN-5024) : remove camel-script-jruby feature

.tool-versions
- https://jira.talendforge.org/browse/TPRUN-5292
Update builder image to use custom builder
add a tool-versions file to specify the needed dependencies
🎾 **Impacts**
=> fix(TPRUN-5292) : add .tools-version for asdf

.tool-versions
- https://jira.talendforge.org/browse/TPRUN-5292
Update builder image to use custom builder
add a tool-versions file to specify the needed dependencies
🎾 **Impacts**
=> fix(TPRUN-5292) add .tool-versions for custom builder

pom.xml
=> TPRUN-5531 woodstox-core update to 6.4.0.

platforms/karaf/features/src/main/resources/features.xml, pom.xml
=> TPRUN-5606 commons-net update to 3.9.0.

camel-dependencies/pom.xml, parent/pom.xml
-   https://jira.talendforge.org/browse/TPRUN-5639
Modification of the Spring version
Modification of the pom file
🎾 **Impacts**
=> fix (TPRUN-5639): spring version update | CVE-2023-20861

pom.xml
=> TPRUN-3588 Camel version corrections.

Jenkinsfile.talend, core/camel-support/pom.xml, core/camel-support/src/main/java/org/apache/camel/support/MessageHelper.java, pom.xml
=> TPRUN-3588 Fix Camel stream handling during logging.

pom.xml
=> TPRUN-5931 Shiro security update to 1.11.0.

Jenkinsfile.talend, components/camel-zookeeper-master/pom.xml, components/camel-zookeeper-master/src/generated/resources/org/apache/camel/component/zookeepermaster/zookeeper-master.json, components/camel-zookeeper-master/src/main/java/org/apache/camel/component/zookeepermaster/group/internal/ZooKeeperGroup.java, components/camel-zookeeper/pom.xml, components/camel-zookeeper/src/generated/resources/org/apache/camel/component/zookeeper/zookeeper.json, pom.xml
=> TPRUN-3588 Update zookeeper and curator in camel-zookeeper components.

pom.xml
- [TPRUN-5850](https://jira.talendforge.org/browse/TPRUN-5850)
Update jetty version
Modification of the pom file
🎾 **Impacts**
=> fix(TPRUN-5850) update jetty version

pom.xml
Includes Netty update to 4.1.100.Final for the same "rapid reset" issue.
=> TPRUN-6915 Jetty update to 9.4.53.v20231009.

components/camel-zookeeper-master/src/generated/resources/org/apache/camel/component/zookeepermaster/zookeeper-master.json, components/camel-zookeeper/src/generated/resources/org/apache/camel/component/zookeeper/zookeeper.json, pom.xml
=> TPRUN-7729 Zookeeper update to 3.8.4.

pom.xml
[TPRUN-8120](https://jira.talendforge.org/browse/TPRUN-8120)
CVE CVE-2024-22201
Update jetty to 9.4.54.v20240208
🎾 **Impacts**
=> fix(TPRUN-8120): update jetty

platforms/karaf/features/src/main/resources/features.xml, pom.xml
commons-io to 2.15.1
james-mime4j to 0.8.11
=> TPRUN-8032 commons-io and mime4j update.

platforms/karaf/features/src/main/resources/features.xml, pom.xml
=> TPRUN-8232 Update of servicemix xerces to latest version.

pom.xml
=> TPRUN-8232 Patch Xerces to accept JAXP 1.5 properties.

platforms/karaf/features/src/main/resources/features.xml, pom.xml
=> TPRUN-8260 Update vulnerable dependencies in Camel features.

platforms/karaf/features/src/main/resources/features.xml, pom.xml
=> TPRUN-8360 Update Xalan version to 2.7.3.

platforms/karaf/features/src/main/resources/features.xml
CVE-2024-5971
CVE-2024-1459
CVE-2024-6162
CVE-2024-27316
CVE-2023-5379
CVE-2023-1973
and further CVEs from older versions
=> TPRUN-8645 Disable undertow 1.x for security reasons.

components/camel-platform-http/src/test/java/org/apache/camel/component/platform/http/PlatformHttpCamelHeadersTest.java, core/camel-core/src/test/java/org/apache/camel/impl/DefaultHeaderFilterStrategyTest.java, core/camel-support/src/main/java/org/apache/camel/support/DefaultHeaderFilterStrategy.java, pom.xml
CVE-2025-27636 - backport of fix from Camel 4.8.5.
=> DPE-852 Fix DefaultHeaderFilterStrategy lowercase filtering.

Jenkinsfile.talend, components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/streaming/ReplayExtension.java, components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/streaming/SubscriptionHelper.java, components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/internal/streaming/SubscriptionHelperTest.java, pom.xml
retrofit of CAMEL-21901 in our branch
=> fix(DPE-1376):  retrofit of CAMEL-21901
